// System Settings (and HUD) expose the 5-theme picker; picking a theme flips the body class + tokens.
import { chromium } from 'playwright';
const SHOTS = '/work/tests/gui/shots';
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: { width: 1366, height: 850 } });
const p = await ctx.newPage();
const errs = [];
p.on('console', m => { if (m.type() === 'error') errs.push(m.text().slice(0, 160)); });
p.on('pageerror', e => errs.push('PE:' + (e.message || e).toString().slice(0, 160)));
await p.goto('http://mymagicdeck.com/', { waitUntil: 'domcontentloaded', timeout: 30000 });
await p.waitForTimeout(2000);
await p.evaluate(() => { try { localStorage.removeItem('mmd_theme'); } catch (e) {} mgLaunchApp('sysset'); });
await p.waitForTimeout(500);
const ss = await p.evaluate(() => ({ picks: document.querySelectorAll('#modal-sysset [data-themepick]').length, bgSwatches: document.querySelectorAll('#modal-sysset [data-bg]').length }));
console.log('System Settings →', JSON.stringify(ss));
const beforeBg = await p.evaluate(() => getComputedStyle(document.body).getPropertyValue('--bg').trim());
await p.click('#modal-sysset [data-themepick="emerald"]');
await p.waitForTimeout(200);
const afterPick = await p.evaluate(() => ({ cls: document.body.classList.contains('theme-emerald'), bg: getComputedStyle(document.body).getPropertyValue('--bg').trim() }));
console.log('beforeBg', beforeBg, '→ after emerald:', JSON.stringify(afterPick));
await p.evaluate(() => { state.user = state.user || { username: 'tester' }; mgLaunchApp('hud'); });
await p.waitForTimeout(400);
const hud = await p.evaluate(() => ({ hudPicks: document.querySelectorAll('#modal-hud [data-themepick], #modal-prog-hud [data-themepick]').length }));
console.log('HUD →', JSON.stringify(hud));
await p.screenshot({ path: SHOTS + '/settings-theme.png' });
await p.evaluate(() => themeSet('dark'));
console.log('CONSOLE_ERRORS:', errs.length, errs.slice(0, 5));
const ok = ss.picks === 5 && ss.bgSwatches > 0 && afterPick.cls && afterPick.bg !== beforeBg && hud.hudPicks === 5 && !errs.length;
console.log('RESULT:', ok ? 'PASS' : 'FAIL');
await b.close();
if (!ok) process.exit(1);
