import { chromium } from 'playwright';
const SHOTS = '/work/tests/gui/shots';
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: { width: 1440, height: 900 } });
const p = await ctx.newPage();
const errs = [];
p.on('console', m => { if (m.type() === 'error') errs.push(m.text().slice(0, 160)); });
p.on('pageerror', e => errs.push('PE:' + (e.message || e).toString().slice(0, 160)));
await p.goto('http://mymagicdeck.com/', { waitUntil: 'domcontentloaded', timeout: 30000 });
await p.waitForTimeout(2000);
await p.click('#deckos-toggle', { timeout: 8000 }); await p.waitForTimeout(1400);
const dbg = await p.evaluate(() => ({ wmOn: document.body.classList.contains('wm-on'), btn: !!document.getElementById('signin-btn'), btnVisible: (() => { const e = document.getElementById('signin-btn'); return e ? getComputedStyle(e).display !== 'none' : false; })(), hasFn: typeof signInClick, hasLaunch: typeof mgLaunchApp, hasAcct: !!(window.MGW_APPS && MGW_APPS.account) }));
console.log('DBG:', JSON.stringify(dbg));
await p.evaluate(() => signInClick());
await p.waitForTimeout(700);
const r = await p.evaluate(() => {
  const modalEl = document.getElementById('auth-modal-title')?.closest('.modal');
  const inWm = !!(modalEl && modalEl.parentElement && modalEl.parentElement.id === 'wm-layer');
  const framed = !!(modalEl && modalEl.classList.contains('wm-win'));
  const visible = !!(modalEl && getComputedStyle(modalEl).display !== 'none' && modalEl.offsetParent !== null) || (modalEl && getComputedStyle(modalEl).display === 'flex');
  const authZ = modalEl ? (parseInt(getComputedStyle(modalEl).zIndex) || 0) : null;
  const siteEl = document.getElementById('site-window');
  const siteZ = siteEl ? (parseInt(getComputedStyle(siteEl).zIndex) || 0) : null;
  return { found: !!modalEl, parent: modalEl?.parentElement?.id, inWmLayer: inWm, framed, visible, authZ, siteZ, authAbove: (authZ != null && siteZ != null) ? authZ >= siteZ : null };
});
console.log(JSON.stringify(r));
await p.screenshot({ path: SHOTS + '/signin-deckos.png' });
console.log('CONSOLE_ERRORS:', errs.length, errs.slice(0, 5));
await b.close();
